version: '3.7'
services:
  flask-app:
    image: localhost:8082/flask-app:latest
    build: ./flask-app
    depends_on:
    - "mysql"
    - "nginx"
  mysql:
    image: localhost:8082/db:latest
    build: ./db
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment:
      MYSQL_ROOT_PASSWORD: root
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
